version: "3"
services:
  minio:
    container_name: data-verifier-minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --address ":9000" --console-address ":9001"
    restart: always
